---
- name: graphene_install
  connection: paramiko
  become: true
  hosts: all
  tasks:
    - name: "Install required libs"
      pip:
        name:
          - colorama
          - coloredlogs
          - terminaltables
          - pyinquirer
          - flask
          - flask-socketio
          - psutil
          - selinux
        executable: /usr/local/bin/pip3.8
        
    - name: "Check if graphenex does not exist"
      ansible.builtin.stat:
        path: /usr/local/lib/python3.8/site-packages/graphenex/modules.json
      register: graphenex_exist
    
    - name: "Install grapheheX on system"
      block:
        - name: "copy grapheheX to python3 libs"
          ansible.builtin.copy:
            src: /vagrant/graphenex/
            dest: /usr/local/lib/python3.8/site-packages/graphenex/
      when: "not graphenex_exist['stat']['exists']"
